### ISSUE TITLE
Project management

### ISSUE THREAD

**Issue by cmmata** [httpsGithubParty/FOSS-for-Dev#2]
I suggest you to make a "Project management" category, and move Redmine there. You could add Phabricator (http://phabricator.org/) and other management software. I can make a PR if you want

**Comment by tvvocold** [comment]
Thx, Send your PR please:)
https://github.com/httpsGithubParty/FOSS-for-Dev/blob/master/README.md#project-management

**Comment by cmmata** [comment]
Done https://github.com/httpsGithubParty/FOSS-for-Dev/pull/3

**Comment by tvvocold** [comment]
Nice!

**Comment by tvvocold** [comment]
BTW,
You are welcome to submit more PR if you like , or consider to [join this party](https://github.com/httpsGithubParty/Join) ! :)
